version: '3'

services:
  db:
    image: prismagraphql/mongo-single-replica:5.0.3
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      INIT_WAIT_SEC: 3
    restart: unless-stopped
    expose:
      - 27017
    healthcheck:
      test:
        [
          'CMD',
          'mongo',
          'admin',
          '--port',
          '27017',
          '--eval',
          "db.adminCommand('ping').ok"
        ]
      interval: 5s
      timeout: 2s
      retries: 20
    ports:
      - 27017:27017

  backend:
    container_name: backend
    build: .
    env_file:
      - .env
    ports:
      - 3001:3001
    expose:
      - 3001
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app:ro
